language: rust
cache: 
  - cargo
  - apt
  
os:
  - linux

rust:
  - stable

matrix:
  include:
    - env:
      - NAME=fanctrlrs
      - TARGET=armv7-unknown-linux-gnueabihf 
      - LINKER=arm-linux-gnueabihf-gcc 
      - PACKAGE=$NAME-rpi3-armv7.tar.gz
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabihf
            - libc6-armhf-cross
            - libc6-dev-armhf-cross
    - env:
      - NAME=fanctrlrs
      - TARGET=aarch64-unknown-linux-gnu	 
      - LINKER=aarch64-linux-gnu-gcc
      - PACKAGE=$NAME-rpi3-aarch64.tar.gz
      addons:
        apt:
          packages:
            - gcc-aarch64-linux-gnu
            - libc6-dev-arm64-cross


install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup target add $TARGET || true
  - echo -e "\ndefault = [\"openssl/vendored\"]\n" >> Cargo.toml
  - echo -e "[dependencies.openssl]\noptional = true\n" >> Cargo.toml
  - |
    if [ -n "$LINKER" ]; then
      mkdir -p ~/.cargo
      echo -e "\n[target.$TARGET]\nlinker = \"$LINKER\"\n" > ~/.cargo/config
    fi
          
script:
  - cargo build --features notify --target $TARGET --verbose --release

before_deploy:
  - cd target/$TARGET/release/
  - mv ${NAME} ${PACKAGE}
  - sha256sum ${PACKAGE} > ${PACKAGE}.sha256

deploy:
  provider: releases
  api_key: 
    secure: $GITHUB_TOKEN
  file: 
    - ${PACKAGE}
    - ${PACKAGE}.sha256
  skip_cleanup: true
  on:
      tags: true